#!/usr/bin/env bash

# yay сам умеет показывать и repo, и AUR обновления
total=$(yay -Qu 2>/dev/null | wc -l || echo 0)

if [[ $total -gt 0 ]]; then
    echo "$total"
    notify-send "󰏕 Updates" "Available $total packages"
else
    echo ""
    notify-send -u low " It's all right" "There are no updates"
fi