#!/usr/bin/env bash
# Обновления из официальных репозиториев (безопасно, не трогает базы)
pacman_updates=$(checkupdates 2>/dev/null | wc -l)

# Обновления из AUR (yay)
aur_updates=$(yay -Qua 2>/dev/null | wc -l)

# Суммируем
total=$((pacman_updates + aur_updates))

# Выводим только если есть обновления (иначе модуль скроется)
if [[ "$total" -gt 0 ]]; then
    notify-send "󰏕 Updates" "Available $total packages"
else
    notify-send -u low " It's all right" "There are no updates"
fi