[config]
#reload_apps = true          # Автоматическая перезагрузка приложений после смены темы
#reload_gtk_theme = true     # Обновлять ли тему GTK

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook   = '''
mkdir -p $HOME/.config/gtk-3.0 $HOME/.config/gtk-4.0;
systemctl --user reset-failed hyprpolkitagent;
systemctl --user restart hyprpolkitagent || true
'''

[templates.color-scheme-qt]
input_path = '~/.config/matugen/templates/Matugen-qt.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.hyprland-lua]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/source/colors.lua'

[templates.vscode-raw]
input_path = './templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = './templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/matugen-colors.conf'
post_hook = "pkill -SIGUSR1 kitty || true"

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.fastfetch]
input_path = '~/.config/matugen/templates/fastfetch.jsonc'
output_path = '~/.config/fastfetch/config.jsonc'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors_git.rasi'
output_path = '~/.config/rofi/colors/matugen-theme.rasi'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync.css'
output_path = '~/.config/swaync/matugen-colors.css'

[templates.swayosd]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swayosd/colors.css'

[templates.papirus]
input_path = "~/.config/matugen/templates/papirus"
output_path = "~/.cache/matugen/papirus"

[templates.startpage]
input_path = "~/.config/matugen/templates/startpage.css"
output_path = "~/.config/chromium/CustomPage/colors.css"