# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e4e2e1"

# Title color for boxes
theme[title]="#bdc9ca"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c4c7c7"

# Background color of selected item in processes box
theme[selected_bg]="#bdc9ca"

# Foreground color of selected item in processes box
theme[selected_fg]="#283233"

# Color of inactive/disabled text
theme[inactive_fg]="#c3c7c7"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c9c4d2"

# Cpu box outline color
theme[cpu_box]="#8d9292"

# Memory/disks box outline color
theme[mem_box]="#8d9292"

# Net up/down box outline color
theme[net_box]="#8d9292"

# Processes box outline color
theme[proc_box]="#8d9292"

# Box divider line and small boxes line color
theme[div_line]="#434848"

# Temperature graph colors
theme[temp_start]="#c4c7c7"
theme[temp_mid]="#bdc9ca"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#c4c7c7"
theme[cpu_mid]="#bdc9ca"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#c4c7c7"
theme[free_mid]=""
theme[free_end]="#434748"

# Mem/Disk cached meter
theme[cached_start]="#c9c4d2"
theme[cached_mid]=""
theme[cached_end]="#0f0e17"

# Mem/Disk available meter
theme[available_start]="#bdc9ca"
theme[available_mid]=""
theme[available_end]="#071112"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#c4c7c7"
theme[download_mid]="#bdc9ca"
theme[download_end]="#c9c4d2"

# Upload graph colors
theme[upload_start]="#c4c7c7"
theme[upload_mid]="#bdc9ca"
theme[upload_end]="#c9c4d2"