-- Generated by matugen (template: ~/.config/matugen/templates/hyprland-colors.lua)
-- Do not edit by hand — this file is overwritten on theme change.

local colors = {
    image = "{{image}}",

<* for name, value in colors *>
    {{name}} = "rgba({{value.default.hex_stripped}}ff)",
<* endfor *>
}

COLORS = colors
return colors
