-- Generated by matugen (template: ~/.config/matugen/templates/hyprland-colors.lua)
-- Do not edit by hand — this file is overwritten on theme change.

local colors = {
    image = "/home/kys/Pictures/Wallpapers/maksim-samuilionak-2nyWutVbBmg-unsplash.jpg",


    background = "rgba(131313ff)",

    error = "rgba(ffb4abff)",

    error_container = "rgba(93000aff)",

    inverse_on_surface = "rgba(303030ff)",

    inverse_primary = "rgba(566061ff)",

    inverse_surface = "rgba(e4e2e1ff)",

    on_background = "rgba(e4e2e1ff)",

    on_error = "rgba(690005ff)",

    on_error_container = "rgba(ffdad6ff)",

    on_primary = "rgba(283233ff)",

    on_primary_container = "rgba(95a0a1ff)",

    on_primary_fixed = "rgba(131d1eff)",

    on_primary_fixed_variant = "rgba(3e494aff)",

    on_secondary = "rgba(2d3131ff)",

    on_secondary_container = "rgba(dee1e1ff)",

    on_secondary_fixed = "rgba(181c1dff)",

    on_secondary_fixed_variant = "rgba(434748ff)",

    on_surface = "rgba(e4e2e1ff)",

    on_surface_variant = "rgba(c3c7c7ff)",

    on_tertiary = "rgba(312f39ff)",

    on_tertiary_container = "rgba(9f9ca8ff)",

    on_tertiary_fixed = "rgba(1c1a24ff)",

    on_tertiary_fixed_variant = "rgba(474550ff)",

    outline = "rgba(8d9292ff)",

    outline_variant = "rgba(434848ff)",

    primary = "rgba(bdc9caff)",

    primary_container = "rgba(071112ff)",

    primary_fixed = "rgba(d9e5e6ff)",

    primary_fixed_dim = "rgba(bdc9caff)",

    scrim = "rgba(000000ff)",

    secondary = "rgba(c4c7c7ff)",

    secondary_container = "rgba(434748ff)",

    secondary_fixed = "rgba(e0e3e3ff)",

    secondary_fixed_dim = "rgba(c4c7c7ff)",

    shadow = "rgba(000000ff)",

    source_color = "rgba(071112ff)",

    surface = "rgba(131313ff)",

    surface_bright = "rgba(393939ff)",

    surface_container = "rgba(1f2020ff)",

    surface_container_high = "rgba(2a2a2aff)",

    surface_container_highest = "rgba(353535ff)",

    surface_container_low = "rgba(1b1c1cff)",

    surface_container_lowest = "rgba(0e0e0eff)",

    surface_dim = "rgba(131313ff)",

    surface_tint = "rgba(bdc9caff)",

    surface_variant = "rgba(434848ff)",

    tertiary = "rgba(c9c4d2ff)",

    tertiary_container = "rgba(0f0e17ff)",

    tertiary_fixed = "rgba(e5e0eeff)",

    tertiary_fixed_dim = "rgba(c9c4d2ff)",

}

COLORS = colors
return colors
